# An introduction to Tensorflow and PyTorch

This notebook is based on the deep learning course and lab provided on the http://introtodeeplearning.com/

In [11]:
#importing necessary libraries.

import tensorflow as tf  #tensorflow
import torch  #PyTorch
from torch import nn #neural network

import numpy as np #numerical computation
import matplotlib.pyplot as plt #for visualization

In [2]:
#checking the versions
tf.__version__, torch.__version__, np.__version__

('2.10.0', '1.12.1+cpu', '1.21.0')

Examples, working with Tensors

In [14]:
#creating tensors in Tensorflow
sport = tf.constant("Soccer", tf.string) # a string
number = tf.constant(1.41421356237, tf.float64) # a float
#rank is the number of dimensions of the tensor, shape represents the size of each dimension.
print(f"Tensorflow\nrank: {tf.rank(sport).numpy()}\nshape: {tf.shape(sport)}")
#*********************************
#*********************************

#PyTorch equivalent

# can't make a string tensor in pytorch
number = torch.tensor(1.143254, dtype = torch.float64)
#dimension only available for 2d
print(f"shape: {number.numpy().shape}")

Tensorflow
rank: 0
shape: []
shape: ()


In [15]:
#Tensorflow
#a random matrix in numpy
matrix_tf = np.random.random(size=(10,2))
#convert it to tensor
matrix_tf = tf.convert_to_tensor(matrix_tf)

#checking
assert isinstance(matrix_tf, tf.Tensor)
assert tf.rank(matrix_tf).numpy() == 2
#***************************

#PyTorch
#a random matrix in numpy
matrixx = np.random.random(size=(10,2))
#convert it to tensor
matrix_pt = torch.as_tensor(matrixx)
#using from_numpy method
matrix_ = torch.from_numpy(matrixx)

#checking
assert isinstance(matrix_pt, torch.Tensor)
assert torch.matrix_rank(matrix_pt).numpy() == 2

In [16]:
#using tensorflow to create matrix of random numbers
mat = tf.random.normal([10,2], dtype= tf.float64)
assert isinstance(mat, tf.Tensor)

#******************
# PyTorch
mat = torch.normal(0,1,size=(10, 2), dtype= torch.float64)
assert isinstance(mat, torch.Tensor)

In [7]:
matrix_tf[1].numpy()

array([0.63426526, 0.67673623])

In [17]:
matrix_pt[1].numpy()

array([0.56662294, 0.05679811])

In [18]:
#TensorFlow
#creating constant tensors
a = tf.constant(5)
b = tf.constant(9)
#addition operation using tensorflow.
c = tf.add(a,b)
#normal addition
c2 = a+b
print(c, c2)

#***************
#PyTorch
a = torch.tensor(5)
b = torch.tensor(9)

c = torch.add(a,b)
c2 = a+b
print(c, c2)

tf.Tensor(14, shape=(), dtype=int32) tf.Tensor(14, shape=(), dtype=int32)
tensor(14) tensor(14)


In [19]:
#TensorFlow
#a custom function
def func(a,b):
  c = tf.add(a,b)
  d = tf.subtract(b,1)
  e = tf.multiply(c,d)

  return e

a, b = 1.5, 2.5

e_out = func(a,b)
print(e_out.numpy())
#***************************
#PyTorch
def func(a,b):
  c = torch.add(a,b)
  d = torch.subtract(b,1)
  e = torch.multiply(c,d)

  return e

a, b = 1.5, 2.5

e_out = func(a,b)
print(e_out.numpy())

6.0
6.0


# Neural Networks in TensorFlow/PyTorch

## TensorFlow

In [20]:
#Tensorflow
# a simple perceptron; y = sigmoid_function(Wx + b)
# Defining a network layer

# n_output_nodes: number of output nodes
# input_shape: shape of the input
# x: input to the layer

class DenseLayer(tf.keras.layers.Layer):
  def __init__(self, n_output_nodes):
    super(DenseLayer, self).__init__()
    self.n_output_nodes = n_output_nodes

  def build(self, input_shape):
    d = int(input_shape[-1])
    self.W = self.add_weight("weight", shape=[d, self.n_output_nodes])
    self.b = self.add_weight("bias", shape=[1, self.n_output_nodes]) 

  def call(self, x):
    z = tf.matmul(x, self.W)
    z = tf.add(z, self.b)

    y = tf.sigmoid(z)

    return y

#fixing the seed
tf.random.set_seed(1)
#creating an instance of our denselayer
layer = DenseLayer(3)
layer.build((1,2))
x_input = tf.constant([[1,2.]], shape=(1,2))
y = layer.call(x_input)

print(y.numpy())

[[0.8964527  0.44808388 0.25748628]]


## PyTorch

In [23]:
#PyTorch implementation of the previous cell
class DenseLayer(nn.Module):
  def __init__(self, n_output_nodes):
    super(DenseLayer, self).__init__()
    self.n_output_nodes = n_output_nodes

  def build(self, input_shape):
    d = int(input_shape[-1])

    self.W = torch.nn.Parameter(torch.empty((d, self.n_output_nodes)))
    self.b = torch.nn.Parameter(torch.empty((1, self.n_output_nodes)))

  def call(self, x):
    z = torch.matmul(x, self.W)
    z = torch.add(z, self.b)

    y = torch.sigmoid(z)

    return y

torch.manual_seed(1)
layer = DenseLayer(3)
layer.build((1,2))
x_input = torch.tensor([[1.0,2.0]])
y = layer.call(x_input)

print(y.detach().numpy())

[[1.         0.50000036 1.        ]]


## Tensorflow

In [25]:
#Defining a neural network using the sequential API
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

n_output_nodes = 3

#first define the model
model = Sequential()
#layer
dense_layer = Dense(n_output_nodes, activation="sigmoid")
model.add(dense_layer)

# Test model with example input
tf.random.set_seed(1)
x_input = tf.constant([[1,2.]], shape=(1,2))
model_output  = model(x_input)
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (1, 3)                    9         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________
None
